apiVersion: v1
kind: Service
metadata:
  name: node-red
spec:
  type: NodePort
  ports:
  - port: 30800
    name: 30800tcp
    targetPort: 1880
    protocol: TCP
    nodePort: 30800
  selector:
    run: node-red
