substitutions:
  plug_name: cam1_32
  mqtt_server: 192.168.202.4
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  
esphome:
  name: ${plug_name}
  platform: ESP32
  # board: nodemcu-32s
  # board: esp32doit-devkit-v1
  board: esp32cam

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  reboot_timeout: 3600s

web_server:
  port: 80
  
# Enable logging
logger:
#   baud_rate: 0

# Enable Home Assistant API
api:

ota:

mqtt:
  broker: ${mqtt_server}
#  port: 1883

esp32_camera:
  name: cam1
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  
  resolution: 640x480
  jpeg_quality: 10
    
sensor:
  - platform: uptime
    name: uptime
  - platform: wifi_signal
    name: Wi-Fi_Signal
    update_interval: 60s
    
