substitutions:
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

esphome:
  name: chrismas
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

# Enable logging
logger:

# Enable Home Assistant API
#api:

ota:

mqtt:
  broker: 192.168.202.4
  
  on_json_message:
    topic: chrismas/light/rahmen/command
    then:
      - light.turn_on:
          id: rahmen
          transition_length: 0s
          brightness: !lambda |-
            if (x.containsKey("state")) {
              if (x["state"] == "DIM") {
                return 1;
              }
              if (x["state"] == "DIMUP") {
                return 0.7;
              }
              if (x["state"] == "DIMDOWN") {
                return 0.3;
              }
            }
            return 0;
#  port: 1883

light:
  - platform: monochromatic
    id: "rahmen"
    name: "rahmen"
    output: output_led
    
    effects:
      - lambda:
          name: dimmerup
          update_interval: 200ms
          lambda: |-
            auto call = id(rahmen).turn_on();
            call.set_transition_length(0);
            static float val = 0;
            static float dir = 1;
            // id(rahmen).current_values_as_brightness(&val);
            val += 0.05 * dir;
            if (val > 1.0) {
              dir = -1;
            }
            if (val < 0.3) {
              dir = 1;
            }
            call.set_brightness(val);
            call.perform();
       
    
output:
  #  pin: GPIO05
  - platform: esp8266_pwm
    id: output_led
    pin: GPIO12
  #- platform: esp8266_pwm
  #  id: output_green
  #  pin: GPIO12
  #- platform: esp8266_pwm
  #  id: output_blue
  #  pin: GPIO13
  # nix pin: GPIO05
  # nix pin: GPIO14
  # nix pin: GPIO13
  # output:
  #   - platform: gpio
  #     pin: GPIO4
  #     id: 'light_switch'
  # switch:
  #   - platform: output
  #     name: "Light-Switch Output"
  #     output: 'light_switch'
  
      
sensor:
  - platform: uptime
    name: uptime
  - platform: wifi_signal
    name: Wi-Fi_Signal
    update_interval: 60s
