substitutions:
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

esphome:
  name: fernseher
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  reboot_timeout: 3600s

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #  ap:
  #  ssid: "Tini Fallback Hotspot"
  #  password: "5FeZ03Jxrwhl"

  #captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

ota:

mqtt:
  broker: 192.168.202.4
#  port: 1883
  

light:
  - platform: neopixelbus
    type: GRBW
    pin: GPIO3
    variant: 800KBPS
    method: ESP8266_DMA
    num_leds: 193
    name: "NeoPixel Light"
    # ...
    effects:
      - addressable_fireworks:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan
      - addressable_twinkle
      
    
sensor:
  - platform: uptime
    name: uptime

  - platform: wifi_signal
    name: Wi-Fi_Signal
    update_interval: 60s
