substitutions:
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

esphome:
  name: koje
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

# Enable logging
logger:

# Enable Home Assistant API
#api:

ota:

mqtt:
  broker: 192.168.202.4
#  port: 1883

light:
  - platform: rgb
    id: "koje"
    name: "Koje"
    red: output_red
    green: output_green
    blue: output_blue
    
# Example output entry
output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO05
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO13
  # nix pin: GPIO05
  # nix pin: GPIO14
  # nix pin: GPIO13
  # output:
  #   - platform: gpio
  #     pin: GPIO4
  #     id: 'light_switch'
  # switch:
  #   - platform: output
  #     name: "Light-Switch Output"
  #     output: 'light_switch'
  
      
sensor:
  - platform: uptime
    name: uptime
  - platform: wifi_signal
    name: Wi-Fi_Signal
    update_interval: 60s
