substitutions:
  plug_name: schrank
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  
esphome:
  name: ${plug_name}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  reboot_timeout: 3600s

# Enable logging
logger:

# Enable Home Assistant API
#api:

ota:

mqtt:
  broker: 192.168.202.4
#  port: 1883

light:
  - platform: neopixelbus
    default_transition_length: 0s
    type: GRBW
    pin: D5
    variant: 400KBPS
    method: BIT_BANG
    num_leds: 21
    name: "schrank-r"
    id: "schrank_r"
    # ...
    #effects:
    #  - addressable_fireworks:
    #  - addressable_rainbow:
      
  - platform: neopixelbus
    default_transition_length: 0s
    type: GRBW
    pin: D6
    variant: 400KBPS
    method: BIT_BANG
    num_leds: 21
    name: "schrank-l"
    id: "schrank_l"
    # ...
    #effects:
    #  - addressable_fireworks:
    #  - addressable_rainbow:

  - platform: monochromatic
    output: schrank_led
    name: "schrank-led"

output:
  - platform: esp8266_pwm
    pin: D1
    frequency: 1000 Hz
    id: schrank_led
    
        
sensor:
  - platform: uptime
    name: uptime
