substitutions:
  plug_name: spiegel_bad
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  mqtt: !secret mqtt
  
esphome:
  name: ${plug_name}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  reboot_timeout: 3600s

# Enable logging
logger:

# Enable Home Assistant API
#api:

ota:

mqtt:
  broker: ${mqtt}
#  port: 1883

light:
  - platform: rgbww
    id: "spiegel_bad"
    name: "spiegel_bad"
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cw
    warm_white: output_ww
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K

output:
  - platform: esp8266_pwm
    id: output_red
    pin: D8
    
  - platform: esp8266_pwm
    id: output_green
    pin: D7

  - platform: esp8266_pwm
    id: output_blue
    pin: D6

    
  - platform: esp8266_pwm
    id: output_cw
    pin: D1
  - platform: esp8266_pwm
    id: output_ww
    pin: D5

    
sensor:
  - platform: uptime
    name: uptime
    
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
