substitutions:
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

esphome:
  name: spiegel_cw
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #  ap:
  #  ssid: "Tini Fallback Hotspot"
  #  password: "5FeZ03Jxrwhl"

  #captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

ota:

mqtt:
  broker: 192.168.202.4
#  port: 1883


light:
  - platform: cwww
    name: "Spiegel CW"
    cold_white: output_cold
    warm_white: output_warm
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    
# Example output entry
output:
  - platform: esp8266_pwm
    id: output_warm
    pin: GPIO05
  - platform: esp8266_pwm
    id: output_cold
    pin: GPIO13
  # nix pin: GPIO05
  # nix pin: GPIO14
  # nix pin: GPIO13
  # output:
  #   - platform: gpio
  #     pin: GPIO4
  #     id: 'light_switch'
  # switch:
  #   - platform: output
  #     name: "Light-Switch Output"
  #     output: 'light_switch'
