substitutions:
  plug_name: wz_decke
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

esphome:
  name: ${plug_name}
  platform: ESP8266
  board: d1_mini
  #includes:
  #  - udp-context.h
  #  - lifx-light.h

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  reboot_timeout: 3600s

# Enable logging
logger:
#  baud_rate: 0

# Enable Home Assistant API
#api:

ota:

mqtt:
  broker: 192.168.202.4
#  port: 1883

light:
  - platform: cwww
    name: "light"
    cold_white: output_ww
    warm_white: output_cw
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K

output:
  - platform: esp8266_pwm
    id: output_ww
    pin: D1

  - platform: esp8266_pwm
    id: output_cw
    pin: D2

sensor:
  #- platform: custom
  #  lambda: |-
  #    auto my_lifx_light = new LifxLight();
  #    App.register_component(my_lifx_light);
  #    return {my_lifx_light};
  #  sensors:
  #    name: "MyLifxLight"

  - platform: uptime
    name: uptime

  - platform: wifi_signal
    name: Wi-Fi_Signal
    update_interval: 60s
